---
language: php
sudo: false
branches:
  only:
    - master
    - 0.1.0
php:
  - 7.0

before_script:
  - composer self-update
  - composer update
script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover --configuration travis-phpunit.xml.dist
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover